// <auto-generated />
using System;
using AU_ERP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AU_ERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428065744_SeedConfigurationSchemasNoCharges")]
    partial class SeedConfigurationSchemasNoCharges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AU_ERP.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PasswordSetupCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AU_ERP.Models.ApplicationUserDepartment", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("PlantID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PlantID");

                    b.ToTable("ApplicationUserDepartments");
                });

            modelBuilder.Entity("AU_ERP.Models.BOMLevelsSample", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelID"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelID");

                    b.ToTable("BOMLevelsSamples");

                    b.HasData(
                        new
                        {
                            LevelID = 1,
                            LevelName = "FG"
                        },
                        new
                        {
                            LevelID = 2,
                            LevelName = "SFG"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.BPGrouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BPGroupings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "local"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.BPRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("BPRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleCode = "FLCU00",
                            RoleName = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            RoleCode = "FLCU01",
                            RoleName = "Customer (Sales)"
                        },
                        new
                        {
                            Id = 3,
                            RoleCode = "FLVN01",
                            RoleName = "Vendor"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeNumberRanges", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<int?>("BPTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<int>("EndNumber")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int");

                    b.HasKey("RangeID");

                    b.HasIndex("BPTypeId");

                    b.ToTable("BPTypeNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BPTypeSamples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeName = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeName = "Vendor"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.Property<int>("BomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BomID"));

                    b.Property<int?>("AlternativeBOM")
                        .HasColumnType("int");

                    b.Property<int?>("BLevel")
                        .HasColumnType("int");

                    b.Property<string>("BOMCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BOMTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BaseQty")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("BomMaterialNumber")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HeaderMaterialTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("BomID");

                    b.HasIndex("AlternativeBOM");

                    b.HasIndex("BLevel");

                    b.HasIndex("Plant");

                    b.ToTable("BomHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomItemsSample", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int?>("BomID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ScrapPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("UomId")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("BomID");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("UomId");

                    b.ToTable("BomItemsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BusinessPartnerMasterSample", b =>
                {
                    b.Property<string>("BPID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BPGroupingId")
                        .HasColumnType("int");

                    b.Property<int?>("BPRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("BPTypeId")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReconAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BPID");

                    b.HasIndex("BPGroupingId");

                    b.HasIndex("BPRoleId");

                    b.HasIndex("BPTypeId");

                    b.ToTable("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DefaultPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("AU_ERP.Models.ConfigurationSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SchemaType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("ConfigurationSchemas");
                });

            modelBuilder.Entity("AU_ERP.Models.ConfigurationSchemaCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargeId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigurationSchemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.HasIndex("ConfigurationSchemaId", "ChargeId")
                        .IsUnique();

                    b.ToTable("ConfigurationSchemaCharges");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveringPlantCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrProcessingTime")
                        .HasColumnType("int");

                    b.Property<string>("GrProcessingUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gr_Processing_UOM");

                    b.Property<string>("IndustrySectorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategoryGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<string>("MaterialGroupCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MrpTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchasingGroupCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ReorderPoint")
                        .HasColumnType("int");

                    b.Property<decimal?>("SafetyStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalesPriceGradeAPerBaseUom")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SalesPriceGradeBPerBaseUom")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SalesPriceGradeCPerBaseUom")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrapCostPerBaseUom")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StrategyGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValuationClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialNumber");

                    b.HasIndex("MaterialGroupCode");

                    b.HasIndex("MaterialTypeCode");

                    b.ToTable("CreateMaterialMaster");
                });

            modelBuilder.Entity("AU_ERP.Models.DeliveryChallan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryChallanNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<string>("PlantId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReferenceSalesOrderNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ShipToBusinessPartnerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShipToDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryChallanNumber")
                        .IsUnique();

                    b.HasIndex("PlantId");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("ShipToBusinessPartnerId");

                    b.ToTable("DeliveryChallans");
                });

            modelBuilder.Entity("AU_ERP.Models.DeliveryChallanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DeliveryChallanId")
                        .HasColumnType("int");

                    b.Property<decimal>("DeliveryQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MaterialDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("QuantityUomId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceSalesOrderNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("SalesOrderItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryChallanId");

                    b.HasIndex("QuantityUomId");

                    b.HasIndex("SalesOrderItemId");

                    b.ToTable("DeliveryChallanItems");
                });

            modelBuilder.Entity("AU_ERP.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Store",
                            Name = "Store"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Sales",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Production",
                            Name = "Production"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Admin",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Finance",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.DistributionChannel", b =>
                {
                    b.Property<int>("DistributionChannelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DistributionChannelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionChannelID"));

                    b.Property<string>("DistributionChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DistributionChannelID");

                    b.ToTable("Distribution_Channel");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentRange", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<int?>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("FromNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ToNumber")
                        .HasColumnType("int");

                    b.HasKey("RangeID");

                    b.HasIndex("DocumentTypeID");

                    b.ToTable("DocumentRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentTypeID");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("AU_ERP.Models.GlobalUnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AltUnitId")
                        .HasColumnType("int");

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AltUnitId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("BaseUnitId", "AltUnitId");

                    b.ToTable("GlobalUnitConversions");
                });

            modelBuilder.Entity("AU_ERP.Models.GoodsProduceBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ProducedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyFirstQuality")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtySecondQuality")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyThirdQuality")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RejectedScrapQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId")
                        .IsUnique();

                    b.ToTable("GoodsProduceBatches");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialGroup", b =>
                {
                    b.Property<string>("MaterialGroupCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorizationGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialGroupCode");

                    b.ToTable("MaterialGroups");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialNumberRange", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<string>("CurrentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RangeID");

                    b.HasIndex("MaterialTypeCode");

                    b.ToTable("MaterialNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialType", b =>
                {
                    b.Property<string>("MaterialTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialTypeCode");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            MaterialTypeCode = "FERT",
                            Description = "Finished products"
                        },
                        new
                        {
                            MaterialTypeCode = "HALB",
                            Description = "Semifinished products"
                        },
                        new
                        {
                            MaterialTypeCode = "PACK",
                            Description = "Packaging"
                        },
                        new
                        {
                            MaterialTypeCode = "ROH",
                            Description = "Raw materials"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.PlantsSample", b =>
                {
                    b.Property<string>("PlantID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantID");

                    b.ToTable("PlantsSamples");

                    b.HasData(
                        new
                        {
                            PlantID = "Emp101",
                            PlantName = "Emporium"
                        },
                        new
                        {
                            PlantID = "Man102",
                            PlantName = "Manufacturing Plant"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinishedMaterialNumber")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PlannedEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReleasedBomSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleasedRoutingId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinishedMaterialNumber");

                    b.HasIndex("ProductionNumber")
                        .IsUnique();

                    b.HasIndex("ReleasedRoutingId");

                    b.HasIndex("UomId");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionOrderStageProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualHours")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("InputQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OutputQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PlannedHours")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("int");

                    b.Property<int>("RoutingOperationHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<string>("StageStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StageTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WastageQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WastageReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkerOperator")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("RoutingOperationHeaderId");

                    b.ToTable("ProductionOrderStageProgresses");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BomId")
                        .HasColumnType("int");

                    b.Property<string>("PlantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RoutingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("PlantId");

                    b.HasIndex("RoutingId");

                    b.ToTable("ProductionVersions");
                });

            modelBuilder.Entity("AU_ERP.Models.PurchaseSchemeRow", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConditionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionID"));

                    b.Property<string>("ConditionSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ConditionID");

                    b.ToTable("Purchase_Scheme");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingHeadersSample", b =>
                {
                    b.Property<int>("RoutingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoutingID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("RoutingID");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("PlantID");

                    b.ToTable("RoutingHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationHeaderSample", b =>
                {
                    b.Property<int>("OperationHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationHeaderId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("RoutingID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("OperationHeaderId");

                    b.HasIndex("RoutingID");

                    b.ToTable("RoutingOperationHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationsSample", b =>
                {
                    b.Property<int>("OpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LaborTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MachineTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("OperationHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("OperationSequence")
                        .HasColumnType("int");

                    b.Property<string>("TimeUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("WorkCenterID")
                        .HasColumnType("int");

                    b.HasKey("OpID");

                    b.HasIndex("OperationHeaderId");

                    b.HasIndex("WorkCenterID");

                    b.ToTable("RoutingOperationsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfigurationSchemaId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerBusinessPartnerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DistributionChannelId")
                        .HasColumnType("int");

                    b.Property<string>("ItemChargeColumnIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentTerm")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlantId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PriceListCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("QuotationChargeValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuotationLevelChargeIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("RequestedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("SalesOrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SalesPersonId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SalesQuotationId")
                        .HasColumnType("int");

                    b.Property<string>("ShipToAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationSchemaId");

                    b.HasIndex("CustomerBusinessPartnerId");

                    b.HasIndex("DistributionChannelId");

                    b.HasIndex("PlantId");

                    b.HasIndex("SalesOrderNumber")
                        .IsUnique();

                    b.HasIndex("SalesQuotationId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemAppliedChargeIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ItemChargeValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineTaxChargeId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("NetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("QuantityUomId")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("SalesPriceGrade")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("SubtotalAfterDiscount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("LineTaxChargeId");

                    b.HasIndex("QuantityUomId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderItems");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesQuotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfigurationSchemaId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerBusinessPartnerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DistributionChannelId")
                        .HasColumnType("int");

                    b.Property<string>("ItemChargeColumnIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PaymentTerm")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlantId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PriceListCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("QuotationChargeValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QuotationDate")
                        .HasColumnType("date");

                    b.Property<string>("QuotationLevelChargeIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SalesPersonId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShipToAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ValidityDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationSchemaId");

                    b.HasIndex("CustomerBusinessPartnerId");

                    b.HasIndex("DistributionChannelId");

                    b.HasIndex("PlantId");

                    b.HasIndex("QuotationNumber")
                        .IsUnique();

                    b.ToTable("SalesQuotations");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesQuotationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemAppliedChargeIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ItemChargeValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineTaxChargeId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("NetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("QuantityUomId")
                        .HasColumnType("int");

                    b.Property<string>("SalesPriceGrade")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SalesQuotationId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalAfterDiscount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("LineTaxChargeId");

                    b.HasIndex("QuantityUomId");

                    b.HasIndex("SalesQuotationId");

                    b.ToTable("SalesQuotationItems");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesSchemaRow", b =>
                {
                    b.Property<int>("ConditionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConditionTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionTypeID"));

                    b.Property<string>("ConditionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SalesType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ConditionTypeID");

                    b.ToTable("Sales_Schema");
                });

            modelBuilder.Entity("AU_ERP.Models.StockInventoryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchOrLot")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuantityUomId")
                        .HasColumnType("int");

                    b.Property<decimal>("StandardCostPerUom")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("StockValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("QuantityUomId");

                    b.HasIndex("Status");

                    b.HasIndex("PlantID", "MaterialNumber", "QuantityUomId", "Status", "Grade")
                        .IsUnique();

                    b.ToTable("StockInventoryLines");
                });

            modelBuilder.Entity("AU_ERP.Models.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AltUnitId")
                        .HasColumnType("int");

                    b.Property<float>("Denominator")
                        .HasColumnType("real");

                    b.Property<int?>("GlobalUnitConversionId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Numerator")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AltUnitId");

                    b.HasIndex("GlobalUnitConversionId");

                    b.HasIndex("MaterialNumber", "AltUnitId")
                        .IsUnique();

                    b.ToTable("UnitConversions");
                });

            modelBuilder.Entity("AU_ERP.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasurements");
                });

            modelBuilder.Entity("AU_ERP.Models.WorkCenterMasterSample", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AvailableCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LaborTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MachineTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("PlantID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("SetupTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TimeUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UtilizationPercentage")
                        .HasColumnType("int");

                    b.Property<string>("WorkCenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PlantID");

                    b.ToTable("WorkCenterMasterSamples");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AU_ERP.Models.ApplicationUserDepartment", b =>
                {
                    b.HasOne("AU_ERP.Models.Department", "Department")
                        .WithMany("UserDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.ApplicationUser", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeNumberRanges", b =>
                {
                    b.HasOne("AU_ERP.Models.BPTypeSample", "TypeSample")
                        .WithMany("BPTypeNumberRanges")
                        .HasForeignKey("BPTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TypeSample");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "AlternativeBom")
                        .WithMany("DependentBomsWithThisAlternative")
                        .HasForeignKey("AlternativeBOM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BOMLevelsSample", "BOMLevel")
                        .WithMany("BomHeadersSamples")
                        .HasForeignKey("BLevel")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.PlantsSample", "PlantSample")
                        .WithMany()
                        .HasForeignKey("Plant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AlternativeBom");

                    b.Navigation("BOMLevel");

                    b.Navigation("PlantSample");
                });

            modelBuilder.Entity("AU_ERP.Models.BomItemsSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "BomHeadersSample")
                        .WithMany("BomItemsSamples")
                        .HasForeignKey("BomID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "CreateMaterialMaster")
                        .WithMany("BomItemsSamples")
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BomHeadersSample");

                    b.Navigation("CreateMaterialMaster");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("AU_ERP.Models.BusinessPartnerMasterSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BPGrouping", "Grouping")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPGroupingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BPRole", "Role")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BPTypeSample", "TypeSample")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grouping");

                    b.Navigation("Role");

                    b.Navigation("TypeSample");
                });

            modelBuilder.Entity("AU_ERP.Models.ConfigurationSchemaCharge", b =>
                {
                    b.HasOne("AU_ERP.Models.Charge", "Charge")
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.ConfigurationSchema", "ConfigurationSchema")
                        .WithMany("SchemaCharges")
                        .HasForeignKey("ConfigurationSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charge");

                    b.Navigation("ConfigurationSchema");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.HasOne("AU_ERP.Models.MaterialGroup", "MaterialGroup")
                        .WithMany("CreateMaterialMasters")
                        .HasForeignKey("MaterialGroupCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.MaterialType", "MaterialType")
                        .WithMany("CreateMaterialMasters")
                        .HasForeignKey("MaterialTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaterialGroup");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("AU_ERP.Models.DeliveryChallan", b =>
                {
                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.SalesOrder", "SalesOrder")
                        .WithMany()
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.BusinessPartnerMasterSample", "ShipToBusinessPartner")
                        .WithMany()
                        .HasForeignKey("ShipToBusinessPartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plant");

                    b.Navigation("SalesOrder");

                    b.Navigation("ShipToBusinessPartner");
                });

            modelBuilder.Entity("AU_ERP.Models.DeliveryChallanItem", b =>
                {
                    b.HasOne("AU_ERP.Models.DeliveryChallan", "DeliveryChallan")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryChallanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "QuantityUom")
                        .WithMany()
                        .HasForeignKey("QuantityUomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.SalesOrderItem", "SalesOrderItem")
                        .WithMany()
                        .HasForeignKey("SalesOrderItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeliveryChallan");

                    b.Navigation("QuantityUom");

                    b.Navigation("SalesOrderItem");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentRange", b =>
                {
                    b.HasOne("AU_ERP.Models.DocumentType", "DocumentType")
                        .WithMany("DocumentRanges")
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("AU_ERP.Models.GlobalUnitConversion", b =>
                {
                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "AltUnit")
                        .WithMany()
                        .HasForeignKey("AltUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AltUnit");

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("AU_ERP.Models.GoodsProduceBatch", b =>
                {
                    b.HasOne("AU_ERP.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("GoodsProduceBatches")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialNumberRange", b =>
                {
                    b.HasOne("AU_ERP.Models.MaterialType", "MaterialType")
                        .WithMany("MaterialNumberRanges")
                        .HasForeignKey("MaterialTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionOrder", b =>
                {
                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "FinishedMaterial")
                        .WithMany()
                        .HasForeignKey("FinishedMaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.RoutingHeadersSample", "ReleasedRouting")
                        .WithMany()
                        .HasForeignKey("ReleasedRoutingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinishedMaterial");

                    b.Navigation("ReleasedRouting");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionOrderStageProgress", b =>
                {
                    b.HasOne("AU_ERP.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("StageProgresses")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.RoutingOperationHeaderSample", "RoutingOperationHeader")
                        .WithMany()
                        .HasForeignKey("RoutingOperationHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("RoutingOperationHeader");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionVersion", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "BomHeader")
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.RoutingHeadersSample", "RoutingHeader")
                        .WithMany()
                        .HasForeignKey("RoutingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BomHeader");

                    b.Navigation("Plant");

                    b.Navigation("RoutingHeader");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingHeadersSample", b =>
                {
                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "Material")
                        .WithMany("RoutingHeadersSamples")
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany("RoutingHeaders")
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationHeaderSample", b =>
                {
                    b.HasOne("AU_ERP.Models.RoutingHeadersSample", "RoutingHeader")
                        .WithMany("OperationHeaders")
                        .HasForeignKey("RoutingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoutingHeader");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationsSample", b =>
                {
                    b.HasOne("AU_ERP.Models.RoutingOperationHeaderSample", "OperationHeader")
                        .WithMany("RoutingOperationsSamples")
                        .HasForeignKey("OperationHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.WorkCenterMasterSample", "WorkCenter")
                        .WithMany("RoutingOperations")
                        .HasForeignKey("WorkCenterID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OperationHeader");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesOrder", b =>
                {
                    b.HasOne("AU_ERP.Models.ConfigurationSchema", "ConfigurationSchema")
                        .WithMany()
                        .HasForeignKey("ConfigurationSchemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.BusinessPartnerMasterSample", "CustomerBusinessPartner")
                        .WithMany()
                        .HasForeignKey("CustomerBusinessPartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.DistributionChannel", "DistributionChannel")
                        .WithMany()
                        .HasForeignKey("DistributionChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.SalesQuotation", "SalesQuotation")
                        .WithMany()
                        .HasForeignKey("SalesQuotationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConfigurationSchema");

                    b.Navigation("CustomerBusinessPartner");

                    b.Navigation("DistributionChannel");

                    b.Navigation("Plant");

                    b.Navigation("SalesQuotation");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesOrderItem", b =>
                {
                    b.HasOne("AU_ERP.Models.Charge", "LineTaxCharge")
                        .WithMany()
                        .HasForeignKey("LineTaxChargeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "QuantityUom")
                        .WithMany()
                        .HasForeignKey("QuantityUomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineTaxCharge");

                    b.Navigation("QuantityUom");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesQuotation", b =>
                {
                    b.HasOne("AU_ERP.Models.ConfigurationSchema", "ConfigurationSchema")
                        .WithMany()
                        .HasForeignKey("ConfigurationSchemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.BusinessPartnerMasterSample", "CustomerBusinessPartner")
                        .WithMany()
                        .HasForeignKey("CustomerBusinessPartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.DistributionChannel", "DistributionChannel")
                        .WithMany()
                        .HasForeignKey("DistributionChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConfigurationSchema");

                    b.Navigation("CustomerBusinessPartner");

                    b.Navigation("DistributionChannel");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesQuotationItem", b =>
                {
                    b.HasOne("AU_ERP.Models.Charge", "LineTaxCharge")
                        .WithMany()
                        .HasForeignKey("LineTaxChargeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "QuantityUom")
                        .WithMany()
                        .HasForeignKey("QuantityUomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AU_ERP.Models.SalesQuotation", "SalesQuotation")
                        .WithMany("Items")
                        .HasForeignKey("SalesQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineTaxCharge");

                    b.Navigation("QuantityUom");

                    b.Navigation("SalesQuotation");
                });

            modelBuilder.Entity("AU_ERP.Models.StockInventoryLine", b =>
                {
                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "QuantityUom")
                        .WithMany()
                        .HasForeignKey("QuantityUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Plant");

                    b.Navigation("QuantityUom");
                });

            modelBuilder.Entity("AU_ERP.Models.UnitConversion", b =>
                {
                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "AltUnit")
                        .WithMany()
                        .HasForeignKey("AltUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.GlobalUnitConversion", "GlobalUnitConversion")
                        .WithMany()
                        .HasForeignKey("GlobalUnitConversionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AltUnit");

                    b.Navigation("GlobalUnitConversion");
                });

            modelBuilder.Entity("AU_ERP.Models.WorkCenterMasterSample", b =>
                {
                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany("WorkCenters")
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AU_ERP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AU_ERP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AU_ERP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AU_ERP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU_ERP.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserDepartments");
                });

            modelBuilder.Entity("AU_ERP.Models.BOMLevelsSample", b =>
                {
                    b.Navigation("BomHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPGrouping", b =>
                {
                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPRole", b =>
                {
                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeSample", b =>
                {
                    b.Navigation("BPTypeNumberRanges");

                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.Navigation("BomItemsSamples");

                    b.Navigation("DependentBomsWithThisAlternative");
                });

            modelBuilder.Entity("AU_ERP.Models.ConfigurationSchema", b =>
                {
                    b.Navigation("SchemaCharges");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.Navigation("BomItemsSamples");

                    b.Navigation("RoutingHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.DeliveryChallan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AU_ERP.Models.Department", b =>
                {
                    b.Navigation("UserDepartments");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentType", b =>
                {
                    b.Navigation("DocumentRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialGroup", b =>
                {
                    b.Navigation("CreateMaterialMasters");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialType", b =>
                {
                    b.Navigation("CreateMaterialMasters");

                    b.Navigation("MaterialNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.PlantsSample", b =>
                {
                    b.Navigation("RoutingHeaders");

                    b.Navigation("WorkCenters");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionOrder", b =>
                {
                    b.Navigation("GoodsProduceBatches");

                    b.Navigation("StageProgresses");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingHeadersSample", b =>
                {
                    b.Navigation("OperationHeaders");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationHeaderSample", b =>
                {
                    b.Navigation("RoutingOperationsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesQuotation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AU_ERP.Models.WorkCenterMasterSample", b =>
                {
                    b.Navigation("RoutingOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
