using System.ComponentModel.DataAnnotations;

namespace AU_ERP.Models
{
    public class MaterialNumberRange
    {
        /// <summary>Surrogate key; generated by SQL Server (IDENTITY).</summary>
        [Key]
        public int RangeID { get; set; }
        public string MaterialTypeCode { get; set; }
        public string FromNumber { get; set; }
        public string ToNumber { get; set; }

        /// <summary>Last issued number in this range; empty or "0" means next issue will be <see cref="FromNumber"/>.</summary>
        public string CurrentNumber { get; set; } = "0";
        public bool IsExternal { get; set; } // bit column

        public virtual MaterialType? MaterialType { get; set; }
    }
}
