// <auto-generated />
using System;
using AU_ERP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AU_ERP.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411111314_AddBusinessPartnerEntities")]
    partial class AddBusinessPartnerEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AU_ERP.Models.BOMLevelsSample", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelID"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelID");

                    b.ToTable("BOMLevelsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPGrouping", b =>
                {
                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("BPGroupings");
                });

            modelBuilder.Entity("AU_ERP.Models.BPNumberRanges", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<string>("BPID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<int>("EndNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int");

                    b.HasKey("RangeID");

                    b.HasIndex("BPID");

                    b.ToTable("BPNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.BPRole", b =>
                {
                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("BPRoles");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeNumberRanges", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<string>("BPType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<int>("EndNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int");

                    b.HasKey("RangeID");

                    b.HasIndex("BPType");

                    b.ToTable("BPTypeNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeSample", b =>
                {
                    b.Property<string>("BPTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BPTypeID");

                    b.ToTable("BPTypeSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.Property<int>("BomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BomID"));

                    b.Property<int?>("AlternativeBOM")
                        .HasColumnType("int");

                    b.Property<int?>("BLevel")
                        .HasColumnType("int");

                    b.Property<decimal?>("BaseQty")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("BomID");

                    b.HasIndex("AlternativeBOM");

                    b.HasIndex("BLevel");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("MaterialTypeCode");

                    b.ToTable("BomHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomItemsSample", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int?>("BomID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ScrapPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("UoM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.HasIndex("BomID");

                    b.HasIndex("MaterialNumber");

                    b.ToTable("BomItemsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BusinessPartnerMasterSample", b =>
                {
                    b.Property<string>("BPID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPGrouping")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BPRole")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BPType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReconAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BPID");

                    b.HasIndex("BPGrouping");

                    b.HasIndex("BPRole");

                    b.HasIndex("BPType");

                    b.ToTable("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvailabilityCheckCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveringPlantCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrProcessingTime")
                        .HasColumnType("int");

                    b.Property<string>("IndustrySectorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategoryGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialGroupCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MrpTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchasingGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrategyGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValuationClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialNumber");

                    b.HasIndex("MaterialGroupCode");

                    b.HasIndex("MaterialTypeCode");

                    b.ToTable("CreateMaterialMaster");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialGroup", b =>
                {
                    b.Property<string>("MaterialGroupCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorizationGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialGroupCode");

                    b.ToTable("MaterialGroups");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialNumberRange", b =>
                {
                    b.Property<string>("RangeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RangeID");

                    b.HasIndex("MaterialTypeCode");

                    b.ToTable("MaterialNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialType", b =>
                {
                    b.Property<string>("MaterialTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialTypeCode");

                    b.ToTable("MaterialTypes");
                });

            modelBuilder.Entity("AU_ERP.Models.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltUnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Denominator")
                        .HasColumnType("real");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Numerator")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("UnitConversions");
                });

            modelBuilder.Entity("AU_ERP.Models.BPNumberRanges", b =>
                {
                    b.HasOne("AU_ERP.Models.BusinessPartnerMasterSample", "BusinessPartner")
                        .WithMany("BPNumberRanges")
                        .HasForeignKey("BPID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessPartner");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeNumberRanges", b =>
                {
                    b.HasOne("AU_ERP.Models.BPTypeSample", "TypeSample")
                        .WithMany("BPTypeNumberRanges")
                        .HasForeignKey("BPType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TypeSample");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "AlternativeBom")
                        .WithMany("DependentBomsWithThisAlternative")
                        .HasForeignKey("AlternativeBOM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BOMLevelsSample", "BOMLevel")
                        .WithMany("BomHeadersSamples")
                        .HasForeignKey("BLevel")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "MaterialMaster")
                        .WithMany()
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.MaterialType", "MaterialType")
                        .WithMany("BomHeadersSamples")
                        .HasForeignKey("MaterialTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AlternativeBom");

                    b.Navigation("BOMLevel");

                    b.Navigation("MaterialMaster");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("AU_ERP.Models.BomItemsSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "BomHeadersSample")
                        .WithMany("BomItemsSamples")
                        .HasForeignKey("BomID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "CreateMaterialMaster")
                        .WithMany("BomItemsSamples")
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BomHeadersSample");

                    b.Navigation("CreateMaterialMaster");
                });

            modelBuilder.Entity("AU_ERP.Models.BusinessPartnerMasterSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BPGrouping", "Grouping")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPGrouping")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BPRole", "Role")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPRole")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BPTypeSample", "TypeSample")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grouping");

                    b.Navigation("Role");

                    b.Navigation("TypeSample");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.HasOne("AU_ERP.Models.MaterialGroup", "MaterialGroup")
                        .WithMany("CreateMaterialMasters")
                        .HasForeignKey("MaterialGroupCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.MaterialType", "MaterialType")
                        .WithMany("CreateMaterialMasters")
                        .HasForeignKey("MaterialTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaterialGroup");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialNumberRange", b =>
                {
                    b.HasOne("AU_ERP.Models.MaterialType", "MaterialType")
                        .WithMany("MaterialNumberRanges")
                        .HasForeignKey("MaterialTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("AU_ERP.Models.BOMLevelsSample", b =>
                {
                    b.Navigation("BomHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPGrouping", b =>
                {
                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPRole", b =>
                {
                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeSample", b =>
                {
                    b.Navigation("BPTypeNumberRanges");

                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.Navigation("BomItemsSamples");

                    b.Navigation("DependentBomsWithThisAlternative");
                });

            modelBuilder.Entity("AU_ERP.Models.BusinessPartnerMasterSample", b =>
                {
                    b.Navigation("BPNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.Navigation("BomItemsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialGroup", b =>
                {
                    b.Navigation("CreateMaterialMasters");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialType", b =>
                {
                    b.Navigation("BomHeadersSamples");

                    b.Navigation("CreateMaterialMasters");

                    b.Navigation("MaterialNumberRanges");
                });
#pragma warning restore 612, 618
        }
    }
}
