// <auto-generated />
using System;
using AU_ERP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AU_ERP.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AU_ERP.Models.BOMLevelsSample", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelID"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelID");

                    b.ToTable("BOMLevelsSamples");

                    b.HasData(
                        new
                        {
                            LevelID = 1,
                            LevelName = "FG"
                        },
                        new
                        {
                            LevelID = 2,
                            LevelName = "SFG"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.BPGrouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BPGroupings");
                });

            modelBuilder.Entity("AU_ERP.Models.BPRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("BPRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleCode = "FLCU00",
                            RoleName = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            RoleCode = "FLCU01",
                            RoleName = "Customer (Sales)"
                        },
                        new
                        {
                            Id = 3,
                            RoleCode = "FLVN01",
                            RoleName = "Vendor"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeNumberRanges", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<int?>("BPTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<int>("EndNumber")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int");

                    b.HasKey("RangeID");

                    b.HasIndex("BPTypeId");

                    b.ToTable("BPTypeNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BPTypeSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.Property<int>("BomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BomID"));

                    b.Property<int?>("AlternativeBOM")
                        .HasColumnType("int");

                    b.Property<int?>("BLevel")
                        .HasColumnType("int");

                    b.Property<string>("BOMCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BOMTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BomMaterialNumber")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("BaseQty")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("HeaderMaterialTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("BomID");

                    b.HasIndex("AlternativeBOM");

                    b.HasIndex("BLevel");

                    b.HasIndex("Plant");

                    b.ToTable("BomHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomItemsSample", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int?>("BomID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ScrapPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("UomId")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("BomID");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("UomId");

                    b.ToTable("BomItemsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BusinessPartnerMasterSample", b =>
                {
                    b.Property<string>("BPID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BPGroupingId")
                        .HasColumnType("int");

                    b.Property<int?>("BPRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("BPTypeId")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReconAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BPID");

                    b.HasIndex("BPGroupingId");

                    b.HasIndex("BPRoleId");

                    b.HasIndex("BPTypeId");

                    b.ToTable("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveringPlantCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrProcessingTime")
                        .HasColumnType("int");

                    b.Property<string>("GrProcessingUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gr_Processing_UOM");

                    b.Property<string>("IndustrySectorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<string>("ItemCategoryGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialGroupCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MrpTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReorderPoint")
                        .HasColumnType("int");

                    b.Property<string>("PurchasingGroupCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SafetyStock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StrategyGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValuationClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialNumber");

                    b.HasIndex("MaterialGroupCode");

                    b.HasIndex("MaterialTypeCode");

                    b.ToTable("CreateMaterialMaster");
                });

            modelBuilder.Entity("AU_ERP.Models.DistributionChannel", b =>
                {
                    b.Property<int>("DistributionChannelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionChannelID"));

                    b.Property<string>("DistributionChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DistributionChannelID");

                    b.ToTable("Distribution_Channel");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentRange", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<int?>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("FromNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ToNumber")
                        .HasColumnType("int");

                    b.HasKey("RangeID");

                    b.HasIndex("DocumentTypeID");

                    b.ToTable("DocumentRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentTypeID");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialGroup", b =>
                {
                    b.Property<string>("MaterialGroupCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorizationGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialGroupCode");

                    b.ToTable("MaterialGroups");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialNumberRange", b =>
                {
                    b.Property<int>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeID"));

                    b.Property<string>("CurrentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RangeID");

                    b.HasIndex("MaterialTypeCode");

                    b.ToTable("MaterialNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialType", b =>
                {
                    b.Property<string>("MaterialTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialTypeCode");

                    b.ToTable("MaterialTypes");
                });

            modelBuilder.Entity("AU_ERP.Models.PlantsSample", b =>
                {
                    b.Property<string>("PlantID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantID");

                    b.ToTable("PlantsSamples");

                    b.HasData(
                        new
                        {
                            PlantID = "Emp101",
                            PlantName = "Emporium"
                        },
                        new
                        {
                            PlantID = "Man102",
                            PlantName = "Manufacturing Plant"
                        });
                });

            modelBuilder.Entity("AU_ERP.Models.PurchaseSchemeRow", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionID"));

                    b.Property<string>("ConditionSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ConditionID");

                    b.ToTable("Purchase_Scheme");
                });

            modelBuilder.Entity("AU_ERP.Models.SalesSchemaRow", b =>
                {
                    b.Property<int>("ConditionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionTypeID"));

                    b.Property<string>("ConditionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SalesType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ConditionTypeID");

                    b.ToTable("Sales_Schema");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BomId")
                        .HasColumnType("int");

                    b.Property<string>("PlantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RoutingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("PlantId");

                    b.HasIndex("RoutingId");

                    b.ToTable("ProductionVersions");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingHeadersSample", b =>
                {
                    b.Property<int>("RoutingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoutingID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("RoutingID");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("PlantID");

                    b.ToTable("RoutingHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationHeaderSample", b =>
                {
                    b.Property<int>("OperationHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationHeaderId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("RoutingID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("OperationHeaderId");

                    b.HasIndex("RoutingID");

                    b.ToTable("RoutingOperationHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationsSample", b =>
                {
                    b.Property<int>("OpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LaborTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MachineTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("OperationHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("OperationSequence")
                        .HasColumnType("int");

                    b.Property<string>("TimeUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("WorkCenterID")
                        .HasColumnType("int");

                    b.HasKey("OpID");

                    b.HasIndex("OperationHeaderId");

                    b.HasIndex("WorkCenterID");

                    b.ToTable("RoutingOperationsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AltUnitId")
                        .HasColumnType("int");

                    b.Property<float>("Denominator")
                        .HasColumnType("real");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Numerator")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AltUnitId");

                    b.ToTable("UnitConversions");
                });

            modelBuilder.Entity("AU_ERP.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasurements");
                });

            modelBuilder.Entity("AU_ERP.Models.WorkCenterMasterSample", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AvailableCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LaborTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MachineTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("PlantID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("SetupTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TimeUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UtilizationPercentage")
                        .HasColumnType("int");

                    b.Property<string>("WorkCenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PlantID");

                    b.ToTable("WorkCenterMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeNumberRanges", b =>
                {
                    b.HasOne("AU_ERP.Models.BPTypeSample", "TypeSample")
                        .WithMany("BPTypeNumberRanges")
                        .HasForeignKey("BPTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TypeSample");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "AlternativeBom")
                        .WithMany("DependentBomsWithThisAlternative")
                        .HasForeignKey("AlternativeBOM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BOMLevelsSample", "BOMLevel")
                        .WithMany("BomHeadersSamples")
                        .HasForeignKey("BLevel")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.PlantsSample", "PlantSample")
                        .WithMany()
                        .HasForeignKey("Plant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AlternativeBom");

                    b.Navigation("BOMLevel");

                    b.Navigation("PlantSample");
                });

            modelBuilder.Entity("AU_ERP.Models.BomItemsSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "BomHeadersSample")
                        .WithMany("BomItemsSamples")
                        .HasForeignKey("BomID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "CreateMaterialMaster")
                        .WithMany("BomItemsSamples")
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BomHeadersSample");

                    b.Navigation("CreateMaterialMaster");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("AU_ERP.Models.BusinessPartnerMasterSample", b =>
                {
                    b.HasOne("AU_ERP.Models.BPGrouping", "Grouping")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPGroupingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BPRole", "Role")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.BPTypeSample", "TypeSample")
                        .WithMany("BusinessPartnerMasterSamples")
                        .HasForeignKey("BPTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grouping");

                    b.Navigation("Role");

                    b.Navigation("TypeSample");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.HasOne("AU_ERP.Models.MaterialGroup", "MaterialGroup")
                        .WithMany("CreateMaterialMasters")
                        .HasForeignKey("MaterialGroupCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.MaterialType", "MaterialType")
                        .WithMany("CreateMaterialMasters")
                        .HasForeignKey("MaterialTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaterialGroup");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentRange", b =>
                {
                    b.HasOne("AU_ERP.Models.DocumentType", "DocumentType")
                        .WithMany("DocumentRanges")
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialNumberRange", b =>
                {
                    b.HasOne("AU_ERP.Models.MaterialType", "MaterialType")
                        .WithMany("MaterialNumberRanges")
                        .HasForeignKey("MaterialTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("AU_ERP.Models.ProductionVersion", b =>
                {
                    b.HasOne("AU_ERP.Models.BomHeadersSample", "BomHeader")
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.RoutingHeadersSample", "RoutingHeader")
                        .WithMany()
                        .HasForeignKey("RoutingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BomHeader");

                    b.Navigation("Plant");

                    b.Navigation("RoutingHeader");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingHeadersSample", b =>
                {
                    b.HasOne("AU_ERP.Models.CreateMaterialMaster", "Material")
                        .WithMany("RoutingHeadersSamples")
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany("RoutingHeaders")
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationHeaderSample", b =>
                {
                    b.HasOne("AU_ERP.Models.RoutingHeadersSample", "RoutingHeader")
                        .WithMany("OperationHeaders")
                        .HasForeignKey("RoutingID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RoutingHeader");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationsSample", b =>
                {
                    b.HasOne("AU_ERP.Models.RoutingOperationHeaderSample", "OperationHeader")
                        .WithMany("RoutingOperationsSamples")
                        .HasForeignKey("OperationHeaderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AU_ERP.Models.WorkCenterMasterSample", "WorkCenter")
                        .WithMany("RoutingOperations")
                        .HasForeignKey("WorkCenterID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OperationHeader");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("AU_ERP.Models.UnitConversion", b =>
                {
                    b.HasOne("AU_ERP.Models.UnitOfMeasurement", "AltUnit")
                        .WithMany()
                        .HasForeignKey("AltUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AltUnit");
                });

            modelBuilder.Entity("AU_ERP.Models.WorkCenterMasterSample", b =>
                {
                    b.HasOne("AU_ERP.Models.PlantsSample", "Plant")
                        .WithMany("WorkCenters")
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("AU_ERP.Models.BOMLevelsSample", b =>
                {
                    b.Navigation("BomHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPGrouping", b =>
                {
                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPRole", b =>
                {
                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BPTypeSample", b =>
                {
                    b.Navigation("BPTypeNumberRanges");

                    b.Navigation("BusinessPartnerMasterSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.BomHeadersSample", b =>
                {
                    b.Navigation("BomItemsSamples");

                    b.Navigation("DependentBomsWithThisAlternative");
                });

            modelBuilder.Entity("AU_ERP.Models.CreateMaterialMaster", b =>
                {
                    b.Navigation("BomItemsSamples");

                    b.Navigation("RoutingHeadersSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.DocumentType", b =>
                {
                    b.Navigation("DocumentRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialGroup", b =>
                {
                    b.Navigation("CreateMaterialMasters");
                });

            modelBuilder.Entity("AU_ERP.Models.MaterialType", b =>
                {
                    b.Navigation("CreateMaterialMasters");

                    b.Navigation("MaterialNumberRanges");
                });

            modelBuilder.Entity("AU_ERP.Models.PlantsSample", b =>
                {
                    b.Navigation("RoutingHeaders");

                    b.Navigation("WorkCenters");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingHeadersSample", b =>
                {
                    b.Navigation("OperationHeaders");
                });

            modelBuilder.Entity("AU_ERP.Models.RoutingOperationHeaderSample", b =>
                {
                    b.Navigation("RoutingOperationsSamples");
                });

            modelBuilder.Entity("AU_ERP.Models.WorkCenterMasterSample", b =>
                {
                    b.Navigation("RoutingOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
